name: 'Deploy To Portainer'
description: 'Deploy with creds'
author: 'Alon B'

inputs:
  project-name:
    description: 'Target project name to deploy'
    default: 'camcode-demo1'
  deployment-env:
    descprtion: 'develop Or prod'
    default: 'develop'  
  current-repo-url:
    descprtion: 'current repository url'
    default: 'https://github.com/VerioN1/cam-code-demo'
  branch-ref:
    descprtion: 'current repository branch ref'
    default: 'refs/heads/main'
  git-user:
    descprtion: 'github Username'
    default: 'username'     
  git-token:
    descprtion: 'Github private repo access token'
    default: '-----'
  docker-compose-file-name:
    descprtion: 'Compose file name for deployment'
    default: 'docker-compose.yml'  
runs:
  using: 'node20'
  main: 'dist/index.js' 
