name: Hello World

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - uses: ./
        with:
          project-name: 'camcode-demo'
          deployment-env: 'develop'
          current-repo-url: 'https://github.com/VerioN1/cam-code-demo'
          branch-ref: 'refs/heads/main'
